[package]
name = "donatello-ffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
raphael-sim = { workspace = true, features = ["serde"] }
raphael-solver = { workspace = true }
gathering-solvers = { workspace = true }
gabriel-solver = { path = "../gabriel-solver" }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"

[lints]
workspace = true
